# Generated by Django 4.0.4 on 2022-11-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_remove_customer_defect_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
