# Generated by Django 4.0.4 on 2022-11-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_customer_reg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='price',
        ),
    ]
