# Generated by Django 4.0.4 on 2022-11-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='email_add',
        ),
    ]
